// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV/GALV_EventSpawnerMZ","status":true,"description":"(v.1.2) Spawn events from a specified spawn map to a desired location.","parameters":{"mId":"2"}},
{"name":"GALV/GALV_MapProjectilesMZ","status":true,"description":"(v.1.1) Create projectiles that can interact with the map and map characters","parameters":{"Fade Speed":"40","premade":""}},
{"name":"Quest/WD_Quest","status":true,"description":"Custom Quest Plugin for RPG Maker MZ","parameters":{"linebreak1":"================","Title":"QuestLog","fontsize":"40","dynamicDescSize":"false","descriptionSize":"20","infoalign":"center","listSize":"20","listAlign":"center","linebreak2":"================","giverprefix":"From:","areaprefix":"Area:","statusname":"Status:","questcompleted":"Completed","questongoing":"Ongoing","questfailed":"Failed","linebreak3":"================","menucommand":"False","commandname":"QuestLog"}},
{"name":"Eli/EliMZ_Book","status":true,"description":"♦5.4.16♦ Essential plugin for all Eli plugins.","parameters":{"engine":"{\"pixelPerfect\":\"true\",\"styleOverflow\":\"false\",\"disableEffekseer\":\"false\",\"--- BUG FIXES ---\":\"\",\"fixBitmapStartLoad\":\"true\"}","playtest":"{\"openDevTools\":\"false\",\"nwWindowPos\":\"0, 0\",\"--- MZ ONLY ---\":\"\",\"gameFocus\":\"true\",\"quickRestart\":\"true\"}"}},
{"name":"Eli/EliMZ_SelfVariables","status":true,"description":"♦2.1.2♦ Self Variables fully integrated with events!","parameters":{"eventIdVar":"0","mapIdVar":"0"}},
{"name":"Eli/EliMZ_ButtonCommonEvents","status":true,"description":"♦5.2.3♦ Bind common events to keyboard/gamepad buttons!","parameters":{"presetKeys":"[\"{\\\"key\\\":\\\"s\\\",\\\"id\\\":\\\"2\\\",\\\"isParallel\\\":\\\"false\\\",\\\"overwrite\\\":\\\"false\\\"}\"]","presetKeysGamePad":"[]"}},
{"name":"SUN/PluginCommonBase","status":true,"description":"Plugin Analysis Common Base","parameters":{}},
{"name":"SUN/Sun_0_GeneratorEx_Setting_Extend","status":true,"description":"SunMZ Character Generator Expansion(setting extension plugin)。","parameters":{"ActorDataList":"[]","WeaponDataList":"[]","ArmorDataList":"[]","VarDataList":"[]"}},
{"name":"SUN/Sun_0_GeneratorEx_Setting_Extend-0","status":true,"description":"SunMZ Character Generator Expansion(setting extension plugin)。","parameters":{"ActorDataList":"[]","WeaponDataList":"[]","ArmorDataList":"[]","VarDataList":"[]"}},
{"name":"SUN/Sun_0_GeneratorEx_Setting_Extend-1","status":true,"description":"SunMZ Character Generator Expansion(setting extension plugin)。","parameters":{"ActorDataList":"[]","WeaponDataList":"[]","ArmorDataList":"[]","VarDataList":"[]"}},
{"name":"SUN/Sun_0_GeneratorEx_Setting_Extend-2","status":true,"description":"SunMZ Character Generator Expansion(setting extension plugin)。","parameters":{"ActorDataList":"[]","WeaponDataList":"[]","ArmorDataList":"[]","VarDataList":"[]"}},
{"name":"SUN/Sun_0_GeneratorEx_Setting_Extend-3","status":true,"description":"SunMZ Character Generator Expansion(setting extension plugin)。","parameters":{"ActorDataList":"[]","WeaponDataList":"[]","ArmorDataList":"[]","VarDataList":"[]"}},
{"name":"SUN/Sun_0_GeneratorEx_Setting_Extend-4","status":true,"description":"SunMZ Character Generator Expansion(setting extension plugin)。","parameters":{"ActorDataList":"[]","WeaponDataList":"[]","ArmorDataList":"[]","VarDataList":"[]"}},
{"name":"SUN/Sun_0_GeneratorEx","status":true,"description":"SunMZ Character Generator Expansion Plugin。","parameters":{"ActorDataList":"[]","WeaponDataList":"[]","ArmorDataList":"[]","VarDataList":"[]","IsSaveSync":"true","FaceTimeoutNum":"100","SvScalingWidth":"0.75","SvScalingHeight":"0.75"}}
];
